resolver 127.0.0.11;
log_format  proxy_log  '[$time_local] $remote_addr - $remote_user "$host$request_uri" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"'
                      ' Proxy: "$proxy_host" "$upstream_addr"';

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

access_log /dev/stdout proxy_log;

server {
    listen 80;
    server_name _;
    location /api {
        set $upstream http://172.33.0.3:8080;
        proxy_pass $upstream;
        proxy_redirect off;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
    location / {
        set $upstream http://172.33.0.4:5173;
        proxy_pass $upstream;
        proxy_redirect off;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
}
